apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myjlcapp
  name: myjlcapp
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myjlcapp
  template:
    metadata:
      labels:
        app: myjlcapp
    spec:
      containers:
      - name: myjlcapp
        image: 192.168.25.200:80/javaproject/bookstore-maven:1.0-SNAPSHOT
        imagePullPolicy: Always
